require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'
source 'https://github.com/sktston/Specs.git'

target 'ReactNativeVcx' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'ReactNativeVcxTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
  
  pod 'vcx', '0.8.2'
end

target 'ReactNativeVcx-tvOS' do
  # Pods for ReactNativeVcx-tvOS

  target 'ReactNativeVcx-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
